#!/bin/sh
set -eu

export HOME="$(mktemp -d)"
export GOCACHE="$HOME/.cache/go-build"
export GOMODCACHE="$HOME/pkg/mod"

mkdir -p "$GOCACHE" "$GOMODCACHE"

command -v restless
restless --help >/dev/null
restless --version
