package cli

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/bspippi1337/restless/internal/core/state"
	"github.com/spf13/cobra"
)

type node struct {
	name     string
	children map[string]*node
}

func newNode(n string) *node {
	return &node{name: n, children: map[string]*node{}}
}

func buildTree(paths []string) *node {
	root := newNode("/")
	for _, p := range paths {
		p = strings.TrimPrefix(strings.TrimSpace(p), "/")
		if p == "" {
			continue
		}
		parts := strings.Split(p, "/")
		cur := root
		for _, part := range parts {
			if part == "" {
				continue
			}
			if cur.children[part] == nil {
				cur.children[part] = newNode(part)
			}
			cur = cur.children[part]
		}
	}
	return root
}

func printTree(n *node, prefix string) {
	keys := make([]string, 0, len(n.children))
	for k := range n.children {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for i, k := range keys {
		child := n.children[k]
		conn := "├─"
		next := prefix + "│ "
		if i == len(keys)-1 {
			conn = "└─"
			next = prefix + "  "
		}
		fmt.Printf("%s%s %s\n", prefix, conn, child.name)
		printTree(child, next)
	}
}

// Minimal SVG writer (README-friendly placeholder).
func writeSVG(path string) error {
	if err := os.MkdirAll("dist", 0o755); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	fmt.Fprintln(f, `<?xml version="1.0" encoding="UTF-8"?>`)
	fmt.Fprintln(f, `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="240">`)
	fmt.Fprintln(f, `<rect width="100%" height="100%" fill="white"/>`)
	fmt.Fprintln(f, `<text x="24" y="40" font-family="monospace" font-size="18">Restless API Topology</text>`)
	fmt.Fprintln(f, `<text x="24" y="70" font-family="monospace" font-size="12">Generated by: restless graph --svg</text>`)
	fmt.Fprintln(f, `</svg>`)
	return nil
}

func NewGraphCmd() *cobra.Command {
	var svg bool

	cmd := &cobra.Command{
		Use:   "graph",
		Short: "Render API topology graph (ASCII, or SVG with --svg).",
		RunE: func(cmd *cobra.Command, args []string) error {
			st, _, err := state.Load()
			if err != nil {
				return err
			}
			if len(st.LastScan.Endpoints) == 0 {
				fmt.Fprintln(cmd.OutOrStdout(), "No endpoints in state. Run: restless discover <url>")
				return nil
			}

			paths := make([]string, 0, len(st.LastScan.Endpoints))
			for _, r := range st.LastScan.Endpoints {
				if strings.TrimSpace(r.Path) != "" {
					paths = append(paths, r.Path)
				}
			}

			fmt.Println("/")
			printTree(buildTree(paths), "")

			if svg {
				if err := writeSVG("dist/api-topology.svg"); err != nil {
					return err
				}
				fmt.Fprintln(cmd.OutOrStdout(), "SVG written to dist/api-topology.svg")
			}
			return nil
		},
	}

	cmd.Flags().BoolVar(&svg, "svg", false, "export svg to dist/api-topology.svg")
	return cmd
}
